# Generated by Django 6.0.3 on 2026-04-25 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscriptionplan_code_subscriptionplan_feature_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('zoom_meeting_id', models.CharField(blank=True, max_length=80)),
                ('zoom_join_url', models.URLField(blank=True)),
                ('zoom_start_url', models.TextField(blank=True)),
                ('zoom_password', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_consultations', to=settings.AUTH_USER_MODEL)),
                ('nutritionist', models.ForeignKey(blank=True, limit_choices_to={'role': 'nutritionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutritionist_consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-id'],
            },
        ),
    ]
