# Generated by Django 6.0.3 on 2026-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, upload_to='blog_images/'),
        ),
    ]
