# Generated by Django 6.0.3 on 2026-04-27 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_blogpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(blank=True, max_length=120)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('image_url', models.TextField(blank=True)),
                ('ai_status', models.CharField(blank=True, max_length=60)),
                ('meal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('meal_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meal_date', '-meal_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('daily_calorie_target', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'nutritionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to='accounts.plantemplate'),
        ),
    ]
