# Generated by Django 6.0.3 on 2026-04-27 20:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_meallog_plantemplate_plan_source_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='meal_time',
            field=models.TimeField(default=accounts.models.current_local_time),
        ),
    ]
