# Generated by Django 6.0.3 on 2026-05-07 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_meallog_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='calories',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
